[#1] 이메일 중복 체크, 닉네임 중복 체크, 회원 가입
f-lab-edu/outstagram pull request #2
Opened 2024-04-11 14:25 UTC by CEO-Nick

## 이메일, 닉네임 중복 체크
- 동일한 이메일, 닉네임으로 회원 가입 방지

## 회원가입
- 회원 가입 진행 시, 한번더 이메일, 닉네임 중복 체크
- 비밀번호는 SHA256을 통해 암호화 처리

2024-04-13 20:53 UTC, f-lab-jason requested changes
전체적으로 컨벤션이 약간 들쑥날쑥한데 google formatter같은걸 적용하는건 어떨까요?

테스트 코드들도 추가해주시면 감사하겠습니다.

2024-04-13 20:53 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/config/MySqlConfig.java
> +    public SqlSessionFactory sqlSessionFactory(DataSource dataSource) throws Exception {
보통 singleton으로 많이 쓰는데 `@Bean`으로 등록하지 않은 이유가 있을까요?

2024-04-13 20:53 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/controller/UserController.java
> +public class UserController {
1. nit: check는 너무 일반적이니 `/check-duplicated-xxxx`같은 형태가 조금 더 좋을 것 같아요!
2. 주석 처리된 작성중인 코드는 어떤 의미인가요?

2024-04-13 20:53 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/dto/UserDTO.java
> +    public static Boolean checkSignupData(UserDTO user) {
1. nit: `validate
2. 이 친구는 개별 클래스에 빼는게 좀 더 좋을 것같아요. 회원가입 전용 메소드인데 userDto안에 있는건 조금 어색한 것 같고 유틸성 메소드이니 `UserDTOValidator`같은데다가 빼는게 더 좋겠습니다.

2024-04-13 20:53 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/service/UserService.java
> +public interface UserService {
nit: 음 저는 service 류가 굳이 interface가 필요하지 않다고 생각해서 대부분 없는걸 더 선호하는데(여러개의 service를 가지는 케이스가 있지 않는 이상) 필요없는건 굳이 넣지 않는것도 괜찮을 것 같아요.

2024-04-13 20:53 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/service/impl/UserServiceImpl.java
> +        String cryptoPassword = encryptSHA256(password);
nit: `encryptedPassword`

2024-04-13 20:53 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/service/impl/UserServiceImpl.java
> +        if (isDuplicatedNickname(userInfo.getNickname())) throw new ApiException(DuplicateErrorCode.DUPLICATED);
validation 류들은 한군데 몰아주시면 더 좋을 것 같아요!

```
public void insertUser(UserDTO userInfo) {
    validateUserInfo(userInfo);
    ...
}

private void validateUserInfo(UserDTO userInfo) {
    validateDuplicatedEmail(userInfo.getEmail());
    validateDuplicatedNickname(userInfo.getNickname());
}

private void validateDuplicatedEmail(String email) { ... }
private void validateDuplicatedNickname(String nickname) { ... }
```

2024-04-14 01:00 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/config/MySqlConfig.java
> +    public SqlSessionFactory sqlSessionFactory(DataSource dataSource) throws Exception {
`@Configuration`으로 설정하면 spring에서 알아서 해준다고 해서 따로 Bean으로 등록 안했습니다.
찾아보니 메서드에도  따로 @Bean 등록을 해야되는군요!! 
수정하겠습니다 ㅎㅎ

2024-04-14 01:03 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/controller/UserController.java
> +public class UserController {
1. 넵, 메서드명 수정하겠습니다!!
2. 주석 처리된 코드는 현재 세션 로그인 구현하다가, 이슈 구분을 해야될 거 같아서 멈췄습니다..ㅎㅎ

2024-04-14 01:06 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/dto/UserDTO.java
> +    public static Boolean checkSignupData(UserDTO user) {
넵!
checkSignupData -> validateSignupData 로 메서드명 수정하고 해당 메서드는 UserDTOValidator 클래스로 빼겠습니다!

2024-04-14 01:08 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/service/UserService.java
> +public interface UserService {
넵 인터페이스 제거하구 UserServiceImpl -> UserService로 수정하겠습니다 ㅎㅎ

2024-04-14 01:25 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/service/impl/UserServiceImpl.java
> +        if (isDuplicatedNickname(userInfo.getNickname())) throw new ApiException(DuplicateErrorCode.DUPLICATED);
UserService 클래스 하단에 몰아넣겠습니다!
근데 컨트롤러 단에서
`@GetMapping("check-email")
    public ResponseEntity<String> checkDuplicatedEmail(@RequestParam String email) {
        Boolean isDuplicate = userService.validateDuplicatedEmail(email);
        if (isDuplicate) {
            return ResponseEntity.status(HttpStatus.CONFLICT).body("이메일이 중복됩니다.");
        } else {
            return ResponseEntity.ok().body("해당 이메일 사용 가능합니다.");
        }
    }`
    
    이렇게 userService의 validateDuplicatedEmail를 사용해야되서 해당 메서드의 접근 제어자를 private가 아닌 public으로 해도 될까요?!

2024-04-14 01:34 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/service/impl/UserServiceImpl.java
> +        String cryptoPassword = encryptSHA256(password);
메서드명 수정하겠습니다 ㅎㅎ

2024-04-14 01:44 UTC, CEO-Nick commented
네 우선 테스트 코드 작성 이외에는 말씀해주신 수정 사항 모두 적용했습니다!!
월요일에 테스트 코드 작성해서 커밋 올리겠습니다!!

2024-04-16 01:41 UTC, f-lab-jason reviewed
음 컨트롤러에 대한 테스트도 추가해주시면 좋겠습니다.
`mockMvc`같은것들의 사용법을 보시면 좋겠네요!

2024-04-16 01:41 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/common/SessionConst.java
> +public class SessionConst {
constant 클래스를 따로 가지는건 좋은 practice 입니다! (util 클래스도 마찬가지구요)
몇가지 추가로 권장되는 사항이 있는데 보통 private constructor를 추가해주고(객체화 하지 못하도록 `@NoArgsConstructor(access = AccessLevel.PRIVATE)`같은걸 붙혀주는 케이스가 많습니다) final 클래스로 선언하는게 선호돼요.

2024-04-16 01:41 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/controller/UserController.java
> +        }
nit: 요런 binary 케이스에는 그냥 else 없이 return만 두는게 조금 더 읽기 쉬운 코드로 선호됩니다. (아래 메소드도 마찬가지구요)

```
if (isDuplicated) {
    return ResponseEntity.status(...
}

return ResponseEntity.ok()...
```

2024-04-16 01:41 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/controller/UserController.java
> +        boolean isDuplicate = userService.validateDuplicatedEmail(email);
nit: `isDuplicated`

2024-04-16 01:41 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/controller/UserController.java
> +                );
음 일단 이 PR에서 고칠 건 아닌데 response에 쓸 공통된 포맷같은게 있으면 좋겠어요.
보통 response에 message, code, isSuccess 정도를 넣어서 공통 포맷으로 쓰는 경우가 많은데(ApiResponse같은 클래스를 하나 만들어서요) 그게 프론트 입장에서는 조금 더 좋을 것 같네요.
이 컨트롤러에서도 요 response는 UserLoginRes 오브젝트로 나가는데 L45같은 경우는 비슷하게 단순 성공 표시인데 body에 plain text로 나가는 등 포맷 정리가 필요할 것 같아요.

2024-04-16 01:41 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/service/UserService.java
> +        }
앗 요런 케이스는..여기에는 그냥 `validateUserInfo(userInfo)` 호출만 있고 validateUserInfo 안에서 exception을 던지는게 조금 더 일반적입니다. 굳이 validateUserInfo의 결과값을 받아서 여기서 처리할 필요가 없으니까요. (다른 validation 메소드들도 마찬가지입니다)

2024-04-16 02:59 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/common/SessionConst.java
> +public class SessionConst {
아하 이해했습니다!! 해당 내용 코드에 적용하겠습니다 ㅎㅎ

2024-04-16 03:02 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/controller/UserController.java
> +                );
새로운 issue 만들어서 ApiResponse 만들어보겠습니다!!
저도 response에 따라 dto를 계속 만들어야 하나 고민했었는데 이렇게 하면 되는군요 ㅎㅎ

2024-04-16 03:09 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/service/UserService.java
> +        }
넵 적용시키겠습니다!!

2024-04-16 03:13 UTC, CEO-Nick commented
## 2번째 PR 리뷰 적용
- SessionConst : 객체화 되지 못하도록 조치
- binary case : else 없이 if문만 사용하는게 더 가독성 좋은 코드
- 메서드명 수정
- exception 처리 레이어 수정

2024-04-17 00:50 UTC, CEO-Nick commented
멘토님, UserController에 대한 test code까지 작성 완료했습니다!

2024-04-19 02:09 UTC, f-lab-jason approved these changes
🚢

2024-04-19 02:09 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/dto/validator/UserDTOValidator.java
> +public class UserDTOValidator {
이거는 쓰이는건가요? 삭제하셔도 무방할 것 같아요.

2024-04-19 03:41 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/dto/validator/UserDTOValidator.java
> +public class UserDTOValidator {
아 애노테이션으로 validation 체크하는 걸로 수정해서 이건 더 이상 필요 없을 거 같습니다 
삭제하겠습니다!

2024-04-19 03:49 UTC, merged