[#24] 좋아요 증가 기능 개발
f-lab-edu/outstagram pull request #25
Opened 2024-04-24 11:01 UTC by CEO-Nick

## 좋아요 증가 기능
- 게시물의 좋아요 개수 1 증가
-  like table에 userId와 postId 기록 -> 어떤 유저가 어떤 게시물을 좋아요 눌렀는지 기록하기 위해 필요

2024-04-25 02:11 UTC, f-lab-jason requested changes
여기도 service들에 대해 테스트가 추가되면 좋겠습니다.

2024-04-25 02:11 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +        }
요 친구는 사실 큰 의미는 없습니다. insert가 성공했다면 result는 0이 될 수 없고, insert가 실패했다면 insert 자체에서 exeption을 던졌을테니 result가 0인 채로 여기 오는 경우는 없다고 생각해도 될 것 같아요. (생각해보니 게시물 PR에도 비슷한게 있었던 것 같아요)

2024-04-25 02:11 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +    public void increaseLike(Long postId, Long userId) {
음 이 부분은 동시성 문제를 고려해보면 좋겠네요. 동시에 두 명이 좋아요를 눌러서 여기로 들어오면 어떻게 될지에 대해 고민해보시면 좋을 것 같아요. (unlike도 마찬가지구요)

2024-04-25 02:11 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +    public List<MyPostsRes> getLikePosts(Long userId) {
paging은 나중에 고려하실 예정이신가요?

2024-04-25 07:35 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +        }
아하, 저는 insert 실패에 대한 예외 처리하기 위해서 저 코드를 작성했었습니다!
생각해보니 애초에 DB에서 exception을 던지겠군요!!
insert 관련 예외 처리 코드는 삭제하겠습니다 ㅎㅎ

2024-04-25 07:37 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +    public void increaseLike(Long postId, Long userId) {
넵, 고민해보겠습니다!
그럼 현재 코드에서는 동시에 두 thread가 접근해서 `increaseLike` 메서드를 수행하면 race condition이 발생할 수 있는건가요?!

2024-04-25 07:39 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +    public List<MyPostsRes> getLikePosts(Long userId) {
앗,,,깜빡했습니다 ㅎㅎ
커서 기반 페이징으로 적용해보겠습니다!

2024-04-25 07:43 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +        }
delete, update의 경우 수정된 게 없다면 result가 0이 되니깐 이에 대한 예외처리는 해야되는게 맞는건가요?!
=

2024-04-25 10:20 UTC, CEO-Nick commented
테스트 코드들도 모두 개발 완료했습니다~

2024-04-26 05:01 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +        }
아 네 이 친구들은 필요합니다!

2024-04-26 05:01 UTC, f-lab-jason commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +    public void increaseLike(Long postId, Long userId) {
네 여러 쓰레드가 동시에 +1을 하면 쓰레드 수만큼 +되는게 아니라 +1만 될테니까요

2024-04-26 05:03 UTC, f-lab-jason approved these changes
동시성같은 케이스는 다른 PR로 수정하시면 좋을 것 같아요 🙂

2024-04-26 09:44 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +        }
넵 남겨두겠습니다!

2024-04-26 09:45 UTC, CEO-Nick commented on src/main/java/com/outstagram/outstagram/service/PostService.java
> +    public void increaseLike(Long postId, Long userId) {
넵!!

2024-04-26 09:46 UTC, CEO-Nick commented
넵, 페이징이랑 동시성 처리는 다른 PR로 수정하겠습니다!

2024-04-26 11:19 UTC, merged